export const productsCache = [
  {
    createdAt: '2022-12-09T06:34:25.607Z',
    product: 'Handmade Metal Shoes',
    points: 16434,
    image: 'https://loremflickr.com/640/480/transport',
    is_redemption: false,
    id: '1',
  },
  {
    createdAt: '2022-12-09T17:02:51.904Z',
    product: 'Recycled Plastic Tuna',
    points: 92984,
    image: 'https://loremflickr.com/640/480/technics',
    is_redemption: false,
    id: '2',
  },
  {
    createdAt: '2022-12-09T10:20:00.909Z',
    product: 'Fantastic Granite Bacon',
    points: 42416,
    image: 'https://loremflickr.com/640/480/technics',
    is_redemption: false,
    id: '3',
  },
  {
    createdAt: '2022-12-09T00:30:23.966Z',
    product: 'Fantastic Fresh Gloves',
    points: 23913,
    image: 'https://loremflickr.com/640/480/city',
    is_redemption: true,
    id: '4',
  },
  {
    createdAt: '2022-12-08T18:54:56.243Z',
    product: 'Rustic Rubber Bacon',
    points: 69814,
    image: 'https://loremflickr.com/640/480/people',
    is_redemption: true,
    id: '5',
  },
  {
    createdAt: '2022-12-09T14:12:11.097Z',
    product: 'Tasty Concrete Cheese',
    points: 81585,
    image: 'https://loremflickr.com/640/480/business',
    is_redemption: false,
    id: '6',
  },
  {
    createdAt: '2022-12-09T12:50:53.209Z',
    product: 'Oriental Cotton Keyboard',
    points: 88323,
    image: 'https://loremflickr.com/640/480/nightlife',
    is_redemption: false,
    id: '7',
  },
  {
    createdAt: '2022-12-08T20:32:14.169Z',
    product: 'Oriental Soft Pants',
    points: 87794,
    image: 'https://loremflickr.com/640/480/animals',
    is_redemption: true,
    id: '8',
  },
  {
    createdAt: '2022-12-09T05:46:47.645Z',
    product: 'Luxurious Rubber Bacon',
    points: 13063,
    image: 'https://loremflickr.com/640/480/food',
    is_redemption: true,
    id: '9',
  },
  {
    createdAt: '2022-12-09T10:56:34.206Z',
    product: 'Elegant Rubber Fish',
    points: 91311,
    image: 'https://loremflickr.com/640/480/transport',
    is_redemption: false,
    id: '10',
  },
  {
    createdAt: '2022-12-09T12:36:43.169Z',
    product: 'Recycled Wooden Salad',
    points: 44871,
    image: 'https://loremflickr.com/640/480/city',
    is_redemption: false,
    id: '11',
  },
  {
    createdAt: '2023-02-04T07:48:16.249Z',
    product: 'Licensed Metal Salad',
    points: 93367,
    image: 'https://loremflickr.com/640/480/food',
    is_redemption: false,
    id: '12',
    from_account_id: 781,
    to_account_id: 369,
    amount: 16,
    verification_code: '8319',
    reason: 'test16',
  },
  {
    createdAt: '2023-02-04T08:45:26.468Z',
    product: 'Ergonomic Plastic Bacon',
    points: 33432,
    image: 'https://loremflickr.com/640/480/food',
    is_redemption: false,
    id: '13',
    from_account_id: 781,
    to_account_id: 369,
    amount: 16,
    verification_code: '8319',
    reason: 'test16',
  },
  {
    createdAt: '2023-03-11T04:50:50.205Z',
    product: 'Ergonomic Granite Fish',
    points: 1314,
    image: 'https://loremflickr.com/640/480/city',
    is_redemption: false,
    id: '14',
    query:
      '\n  query IntrospectionQuery {\n    __schema {\n      queryType { name }\n      mutationType { name }\n      subscriptionType { name }\n      types {\n        ...FullType\n      }\n      directives {\n        name\n        description\n        locations\n        args {\n          ...InputValue\n        }\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields(includeDeprecated: true) {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      type {\n        ...TypeRef\n      }\n      isDeprecated\n      deprecationReason\n    }\n    inputFields {\n      ...InputValue\n    }\n    interfaces {\n      ...TypeRef\n    }\n    enumValues(includeDeprecated: true) {\n      name\n      description\n      isDeprecated\n      deprecationReason\n    }\n    possibleTypes {\n      ...TypeRef\n    }\n  }\n\n  fragment InputValue on __InputValue {\n    name\n    description\n    type { ...TypeRef }\n    defaultValue\n  }\n\n  fragment TypeRef on __Type {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n                ofType {\n                  kind\n                  name\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n',
  },
  {
    createdAt: '2023-03-11T04:35:35.259Z',
    product: 'Small Frozen Shirt',
    points: 55894,
    image: 'https://loremflickr.com/640/480/business',
    is_redemption: true,
    id: '15',
    query:
      '\n  query IntrospectionQuery {\n    __schema {\n      queryType { name }\n      mutationType { name }\n      types {\n        ...FullType\n      }\n      directives {\n        name\n        description\n        locations\n        args {\n          ...InputValue\n        }\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields(includeDeprecated: true) {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      type {\n        ...TypeRef\n      }\n      isDeprecated\n      deprecationReason\n    }\n    inputFields {\n      ...InputValue\n    }\n    interfaces {\n      ...TypeRef\n    }\n    enumValues(includeDeprecated: true) {\n      name\n      description\n      isDeprecated\n      deprecationReason\n    }\n    possibleTypes {\n      ...TypeRef\n    }\n  }\n\n  fragment InputValue on __InputValue {\n    name\n    description\n    type { ...TypeRef }\n    defaultValue\n  }\n\n  fragment TypeRef on __Type {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n                ofType {\n                  kind\n                  name\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n',
  },
  {
    createdAt: '2023-03-11T07:49:58.766Z',
    product: 'Electronic Bronze Salad',
    points: 21880,
    image: 'https://loremflickr.com/640/480/transport',
    is_redemption: false,
    id: '16',
    query:
      '\n# Welcome to GraphiQL\n#\n# GraphiQL is an in-browser tool for writing, validating, and\n# testing GraphQL queries.\n#\n# Type queries into this side of the screen, and you will see intelligent\n# typeaheads aware of the current GraphQL type schema and live syntax and\n# validation errors highlighted within the text.\n#\n# GraphQL queries typically start with a "{" character. Lines that starts\n# with a # are ignored.\n#\n# An example GraphQL query might look like:\n#\n#     {\n#       field(arg: "value") {\n#         subField\n#       }\n#     }\n#\n# Keyboard shortcuts:\n#\n#       Run Query:  Ctrl-Enter (or press the play button above)\n#\n#   Auto Complete:  Ctrl-Space (or just start typing)\n#\n# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #\n# Default endpoint is an instance of https://www.graph.cool/\n# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #\n\nquery {\n  movements {\n    product\n  }\n}\n',
    variables: null,
  },
  {
    createdAt: '2023-03-11T13:57:33.428Z',
    product: 'Refined Concrete Pizza',
    points: 51314,
    image: 'https://loremflickr.com/640/480/city',
    is_redemption: true,
    id: '17',
    query:
      '\n# Welcome to GraphiQL\n#\n# GraphiQL is an in-browser tool for writing, validating, and\n# testing GraphQL queries.\n#\n# Type queries into this side of the screen, and you will see intelligent\n# typeaheads aware of the current GraphQL type schema and live syntax and\n# validation errors highlighted within the text.\n#\n# GraphQL queries typically start with a "{" character. Lines that starts\n# with a # are ignored.\n#\n# An example GraphQL query might look like:\n#\n#     {\n#       field(arg: "value") {\n#         subField\n#       }\n#     }\n#\n# Keyboard shortcuts:\n#\n#       Run Query:  Ctrl-Enter (or press the play button above)\n#\n#   Auto Complete:  Ctrl-Space (or just start typing)\n#\n# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #\n# Default endpoint is an instance of https://www.graph.cool/\n# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #\n\nquery {\n  products {\n    product\n  }\n}\n',
    variables: null,
  },
  {
    createdAt: '2023-03-11T12:17:47.118Z',
    product: 'Elegant Concrete Chips',
    points: 57955,
    image: 'https://loremflickr.com/640/480/business',
    is_redemption: false,
    id: '18',
    query:
      '\n# Welcome to GraphiQL\n#\n# GraphiQL is an in-browser tool for writing, validating, and\n# testing GraphQL queries.\n#\n# Type queries into this side of the screen, and you will see intelligent\n# typeaheads aware of the current GraphQL type schema and live syntax and\n# validation errors highlighted within the text.\n#\n# GraphQL queries typically start with a "{" character. Lines that starts\n# with a # are ignored.\n#\n# An example GraphQL query might look like:\n#\n#     {\n#       field(arg: "value") {\n#         subField\n#       }\n#     }\n#\n# Keyboard shortcuts:\n#\n#       Run Query:  Ctrl-Enter (or press the play button above)\n#\n#   Auto Complete:  Ctrl-Space (or just start typing)\n#\n# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #\n# Default endpoint is an instance of https://www.graph.cool/\n# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #\n\nquery {\n  products {\n    product\n  }\n}\n',
    variables: null,
  },
  {
    createdAt: '2023-03-11T07:59:31.773Z',
    product: 'Licensed Concrete Shirt',
    points: 35936,
    image: 'https://loremflickr.com/640/480/fashion',
    is_redemption: true,
    id: '19',
    query:
      '\n# Welcome to GraphiQL\n#\n# GraphiQL is an in-browser tool for writing, validating, and\n# testing GraphQL queries.\n#\n# Type queries into this side of the screen, and you will see intelligent\n# typeaheads aware of the current GraphQL type schema and live syntax and\n# validation errors highlighted within the text.\n#\n# GraphQL queries typically start with a "{" character. Lines that starts\n# with a # are ignored.\n#\n# An example GraphQL query might look like:\n#\n#     {\n#       field(arg: "value") {\n#         subField\n#       }\n#     }\n#\n# Keyboard shortcuts:\n#\n#       Run Query:  Ctrl-Enter (or press the play button above)\n#\n#   Auto Complete:  Ctrl-Space (or just start typing)\n#\n# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #\n# Default endpoint is an instance of https://www.graph.cool/\n# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #\n\nquery {\n  products {\n    \n  }\n}\n',
    variables: null,
  },
  {
    createdAt: '2023-03-11T12:25:04.499Z',
    product: 'Oriental Bronze Gloves',
    points: 18576,
    image: 'https://loremflickr.com/640/480/technics',
    is_redemption: false,
    id: '20',
    query:
      '\n    query IntrospectionQuery {\n      __schema {\n        \n        queryType { name }\n        mutationType { name }\n        subscriptionType { name }\n        types {\n          ...FullType\n        }\n        directives {\n          name\n          description\n          \n          locations\n          args {\n            ...InputValue\n          }\n        }\n      }\n    }\n\n    fragment FullType on __Type {\n      kind\n      name\n      description\n      \n      fields(includeDeprecated: true) {\n        name\n        description\n        args {\n          ...InputValue\n        }\n        type {\n          ...TypeRef\n        }\n        isDeprecated\n        deprecationReason\n      }\n      inputFields {\n        ...InputValue\n      }\n      interfaces {\n        ...TypeRef\n      }\n      enumValues(includeDeprecated: true) {\n        name\n        description\n        isDeprecated\n        deprecationReason\n      }\n      possibleTypes {\n        ...TypeRef\n      }\n    }\n\n    fragment InputValue on __InputValue {\n      name\n      description\n      type { ...TypeRef }\n      defaultValue\n      \n      \n    }\n\n    fragment TypeRef on __Type {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n                ofType {\n                  kind\n                  name\n                  ofType {\n                    kind\n                    name\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  ',
    variables: {},
    operationName: 'IntrospectionQuery',
  },
  {
    createdAt: '2023-03-11T13:55:54.446Z',
    product: 'Electronic Frozen Bacon',
    points: 67223,
    image: 'https://loremflickr.com/640/480/people',
    is_redemption: true,
    id: '21',
    query:
      '# Welcome to Altair GraphQL Client.\n# You can send your request using CmdOrCtrl + Enter.\n\n# Enter your graphQL query here.\n',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T04:44:24.722Z',
    product: 'Awesome Soft Chair',
    points: 28855,
    image: 'https://loremflickr.com/640/480/business',
    is_redemption: false,
    id: '22',
    query: '{\n  products\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T15:03:45.467Z',
    product: 'Gorgeous Cotton Sausages',
    points: 31023,
    image: 'https://loremflickr.com/640/480/nightlife',
    is_redemption: true,
    id: '23',
    query: '{\n  \n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T10:55:49.835Z',
    product: 'Incredible Steel Hat',
    points: 27667,
    image: 'https://loremflickr.com/640/480/sports',
    is_redemption: false,
    id: '24',
    query: '{\n  products {\n    image\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-10T21:42:22.255Z',
    product: 'Recycled Concrete Computer',
    points: 5541,
    image: 'https://loremflickr.com/640/480/city',
    is_redemption: false,
    id: '25',
    query: '\nproducts {\n    image\n  }\n',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T20:17:03.897Z',
    product: 'Awesome Metal Shoes',
    points: 9549,
    image: 'https://loremflickr.com/640/480/food',
    is_redemption: false,
    id: '26',
    query: '\n {\n    image\n  }\n',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T09:40:54.176Z',
    product: 'Small Concrete Fish',
    points: 17898,
    image: 'https://loremflickr.com/640/480/cats',
    is_redemption: true,
    id: '27',
    query: '\n {\n    image\n}\n',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T14:32:46.716Z',
    product: 'Generic Frozen Keyboard',
    points: 36843,
    image: 'https://loremflickr.com/640/480/sports',
    is_redemption: true,
    id: '28',
    query: '{\n    image\n}\n',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T09:38:23.201Z',
    product: 'Fantastic Wooden Chicken',
    points: 18983,
    image: 'https://loremflickr.com/640/480/transport',
    is_redemption: true,
    id: '29',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T13:01:48.198Z',
    product: 'Modern Soft Mouse',
    points: 2055,
    image: 'https://loremflickr.com/640/480/nature',
    is_redemption: false,
    id: '30',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T10:56:03.463Z',
    product: 'Fantastic Granite Cheese',
    points: 52029,
    image: 'https://loremflickr.com/640/480/sports',
    is_redemption: false,
    id: '31',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T06:38:35.316Z',
    product: 'Modern Concrete Pants',
    points: 20949,
    image: 'https://loremflickr.com/640/480/business',
    is_redemption: false,
    id: '32',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T18:28:13.699Z',
    product: 'Incredible Rubber Ball',
    points: 46005,
    image: 'https://loremflickr.com/640/480/nature',
    is_redemption: true,
    id: '33',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-10T21:29:58.790Z',
    product: 'Recycled Concrete Chair',
    points: 10929,
    image: 'https://loremflickr.com/640/480/transport',
    is_redemption: false,
    id: '34',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T02:32:38.065Z',
    product: 'Refined Rubber Shoes',
    points: 64053,
    image: 'https://loremflickr.com/640/480/nightlife',
    is_redemption: true,
    id: '35',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T14:18:37.791Z',
    product: 'Tasty Wooden Soap',
    points: 90285,
    image: 'https://loremflickr.com/640/480/cats',
    is_redemption: true,
    id: '36',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T10:30:16.070Z',
    product: 'Bespoke Fresh Bacon',
    points: 45690,
    image: 'https://loremflickr.com/640/480/food',
    is_redemption: false,
    id: '37',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T14:53:19.410Z',
    product: 'Elegant Wooden Tuna',
    points: 64684,
    image: 'https://loremflickr.com/640/480/abstract',
    is_redemption: true,
    id: '38',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-10T22:23:08.642Z',
    product: 'Unbranded Plastic Computer',
    points: 57294,
    image: 'https://loremflickr.com/640/480/animals',
    is_redemption: true,
    id: '39',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T04:53:25.920Z',
    product: 'Awesome Wooden Keyboard',
    points: 55476,
    image: 'https://loremflickr.com/640/480/fashion',
    is_redemption: false,
    id: '40',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T02:58:18.166Z',
    product: 'Ergonomic Granite Salad',
    points: 54324,
    image: 'https://loremflickr.com/640/480/transport',
    is_redemption: false,
    id: '41',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T19:55:44.192Z',
    product: 'Luxurious Soft Soap',
    points: 78611,
    image: 'https://loremflickr.com/640/480/nature',
    is_redemption: true,
    id: '42',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T12:34:48.009Z',
    product: 'Incredible Rubber Salad',
    points: 4872,
    image: 'https://loremflickr.com/640/480/nature',
    is_redemption: false,
    id: '43',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-10T23:23:08.002Z',
    product: 'Handcrafted Frozen Gloves',
    points: 10425,
    image: 'https://loremflickr.com/640/480/animals',
    is_redemption: true,
    id: '44',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-10T22:59:27.000Z',
    product: 'Rustic Soft Fish',
    points: 50208,
    image: 'https://loremflickr.com/640/480/fashion',
    is_redemption: false,
    id: '45',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T17:37:37.831Z',
    product: 'Tasty Frozen Cheese',
    points: 99918,
    image: 'https://loremflickr.com/640/480/fashion',
    is_redemption: true,
    id: '46',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T06:14:07.143Z',
    product: 'Electronic Rubber Pants',
    points: 28760,
    image: 'https://loremflickr.com/640/480/transport',
    is_redemption: true,
    id: '47',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-10T21:53:16.125Z',
    product: 'Small Wooden Shoes',
    points: 18255,
    image: 'https://loremflickr.com/640/480/nightlife',
    is_redemption: false,
    id: '48',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T08:57:47.148Z',
    product: 'Sleek Wooden Salad',
    points: 66039,
    image: 'https://loremflickr.com/640/480/cats',
    is_redemption: true,
    id: '49',
    query:
      'query {\n  products {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T11:24:20.749Z',
    product: 'Handmade Plastic Tuna',
    points: 89798,
    image: 'https://loremflickr.com/640/480/nature',
    is_redemption: true,
    id: '50',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T05:27:55.982Z',
    product: 'Awesome Concrete Soap',
    points: 53810,
    image: 'https://loremflickr.com/640/480/nightlife',
    is_redemption: true,
    id: '51',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T05:36:26.969Z',
    product: 'Bespoke Soft Pants',
    points: 12336,
    image: 'https://loremflickr.com/640/480/city',
    is_redemption: false,
    id: '52',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T17:15:30.511Z',
    product: 'Unbranded Soft Bacon',
    points: 66774,
    image: 'https://loremflickr.com/640/480/business',
    is_redemption: false,
    id: '53',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-10T21:03:53.167Z',
    product: 'Licensed Rubber Salad',
    points: 84712,
    image: 'https://loremflickr.com/640/480/nightlife',
    is_redemption: true,
    id: '54',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T19:35:57.342Z',
    product: 'Tasty Soft Cheese',
    points: 49194,
    image: 'https://loremflickr.com/640/480/business',
    is_redemption: false,
    id: '55',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T01:32:26.820Z',
    product: 'Licensed Wooden Gloves',
    points: 498,
    image: 'https://loremflickr.com/640/480/city',
    is_redemption: true,
    id: '56',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-10T23:56:00.690Z',
    product: 'Small Granite Hat',
    points: 41388,
    image: 'https://loremflickr.com/640/480/nightlife',
    is_redemption: true,
    id: '57',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T01:58:51.907Z',
    product: 'Small Soft Chair',
    points: 95413,
    image: 'https://loremflickr.com/640/480/animals',
    is_redemption: true,
    id: '58',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T09:11:38.503Z',
    product: 'Rustic Bronze Shoes',
    points: 3171,
    image: 'https://loremflickr.com/640/480/transport',
    is_redemption: true,
    id: '59',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T20:22:31.622Z',
    product: 'Gorgeous Steel Bacon',
    points: 71170,
    image: 'https://loremflickr.com/640/480/food',
    is_redemption: false,
    id: '60',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-10T23:04:46.521Z',
    product: 'Intelligent Steel Towels',
    points: 22337,
    image: 'https://loremflickr.com/640/480/business',
    is_redemption: false,
    id: '61',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T03:45:24.860Z',
    product: 'Fantastic Steel Salad',
    points: 19825,
    image: 'https://loremflickr.com/640/480/sports',
    is_redemption: false,
    id: '62',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T08:58:17.580Z',
    product: 'Ergonomic Cotton Soap',
    points: 39581,
    image: 'https://loremflickr.com/640/480/fashion',
    is_redemption: true,
    id: '63',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T17:21:42.140Z',
    product: 'Recycled Soft Hat',
    points: 73631,
    image: 'https://loremflickr.com/640/480/cats',
    is_redemption: false,
    id: '64',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T09:21:19.019Z',
    product: 'Tasty Bronze Pizza',
    points: 18715,
    image: 'https://loremflickr.com/640/480/people',
    is_redemption: true,
    id: '65',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T02:34:20.641Z',
    product: 'Oriental Fresh Keyboard',
    points: 86764,
    image: 'https://loremflickr.com/640/480/cats',
    is_redemption: true,
    id: '66',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-10T23:59:44.161Z',
    product: 'Small Plastic Computer',
    points: 10681,
    image: 'https://loremflickr.com/640/480/people',
    is_redemption: true,
    id: '67',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T20:37:24.687Z',
    product: 'Modern Frozen Salad',
    points: 12385,
    image: 'https://loremflickr.com/640/480/abstract',
    is_redemption: false,
    id: '68',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T07:16:39.079Z',
    product: 'Ergonomic Soft Tuna',
    points: 11149,
    image: 'https://loremflickr.com/640/480/technics',
    is_redemption: false,
    id: '69',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T09:54:51.507Z',
    product: 'Luxurious Steel Gloves',
    points: 70098,
    image: 'https://loremflickr.com/640/480/sports',
    is_redemption: false,
    id: '70',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T20:51:47.416Z',
    product: 'Luxurious Metal Cheese',
    points: 72922,
    image: 'https://loremflickr.com/640/480/transport',
    is_redemption: false,
    id: '71',
    operationName: 'Chapters',
    variables: {},
    query:
      'query Chapters {\n  chapters {\n    id\n    number\n    title\n    __typename\n  }\n}\n',
  },
  {
    createdAt: '2023-03-11T12:52:41.909Z',
    product: 'Intelligent Plastic Towels',
    points: 51279,
    image: 'https://loremflickr.com/640/480/city',
    is_redemption: true,
    id: '72',
    operationName: 'Chapters',
    variables: {},
    query:
      'query Chapters {\n  chapters {\n    id\n    number\n    title\n    __typename\n  }\n}\n',
  },
  {
    createdAt: '2023-03-11T20:40:42.802Z',
    product: 'Handcrafted Granite Sausages',
    points: 1334,
    image: 'https://loremflickr.com/640/480/cats',
    is_redemption: true,
    id: '73',
    operationName: 'Chapters',
    variables: {},
    query:
      'query Chapters {\n  chapters {\n    id\n    number\n    title\n    __typename\n  }\n}\n',
  },
  {
    createdAt: '2023-03-11T15:14:39.908Z',
    product: 'Sleek Frozen Chicken',
    points: 11837,
    image: 'https://loremflickr.com/640/480/animals',
    is_redemption: false,
    id: '74',
    operationName: 'AllProducts',
    variables: {},
    query:
      'query AllProducts {\n  product {\n    id\n    number\n    title\n    __typename\n  }\n}\n',
  },
  {
    createdAt: '2023-03-11T13:42:18.901Z',
    product: 'Handmade Frozen Keyboard',
    points: 3134,
    image: 'https://loremflickr.com/640/480/technics',
    is_redemption: false,
    id: '75',
    variables: {},
    query:
      '{\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n    __typename\n  }\n}\n',
  },
  {
    createdAt: '2023-03-11T18:05:23.913Z',
    product: 'Gorgeous Plastic Tuna',
    points: 73860,
    image: 'https://loremflickr.com/640/480/business',
    is_redemption: true,
    id: '76',
    variables: {},
    query:
      '{\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n    __typename\n  }\n}\n',
  },
  {
    createdAt: '2023-03-11T16:46:16.239Z',
    product: 'Small Bronze Hat',
    points: 65980,
    image: 'https://loremflickr.com/640/480/food',
    is_redemption: true,
    id: '77',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T15:32:29.957Z',
    product: 'Refined Cotton Sausages',
    points: 62506,
    image: 'https://loremflickr.com/640/480/business',
    is_redemption: false,
    id: '78',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T10:10:31.677Z',
    product: 'Elegant Frozen Ball',
    points: 27106,
    image: 'https://loremflickr.com/640/480/business',
    is_redemption: false,
    id: '79',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T22:01:54.952Z',
    product: 'Elegant Steel Cheese',
    points: 74447,
    image: 'https://loremflickr.com/640/480/food',
    is_redemption: false,
    id: '80',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T17:43:44.160Z',
    product: 'Luxurious Wooden Mouse',
    points: 36544,
    image: 'https://loremflickr.com/640/480/transport',
    is_redemption: true,
    id: '81',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T08:39:51.035Z',
    product: 'Intelligent Steel Towels',
    points: 77148,
    image: 'https://loremflickr.com/640/480/nightlife',
    is_redemption: true,
    id: '82',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T10:43:44.406Z',
    product: 'Unbranded Rubber Towels',
    points: 68238,
    image: 'https://loremflickr.com/640/480/animals',
    is_redemption: true,
    id: '83',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T19:18:38.110Z',
    product: 'Fantastic Concrete Ball',
    points: 68692,
    image: 'https://loremflickr.com/640/480/nature',
    is_redemption: false,
    id: '84',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T17:06:33.899Z',
    product: 'Modern Bronze Computer',
    points: 21715,
    image: 'https://loremflickr.com/640/480/nightlife',
    is_redemption: true,
    id: '85',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T09:09:53.413Z',
    product: 'Fantastic Plastic Computer',
    points: 40289,
    image: 'https://loremflickr.com/640/480/abstract',
    is_redemption: false,
    id: '86',
    query:
      'query {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-12T01:50:13.136Z',
    product: 'Awesome Fresh Soap',
    points: 72170,
    image: 'https://loremflickr.com/640/480/people',
    is_redemption: true,
    id: '87',
    query:
      'query query_allProducts_id377 {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}\n',
    variables: {},
    operationName: 'query_allProducts_id377',
  },
  {
    createdAt: '2023-03-11T13:59:55.463Z',
    product: 'Oriental Frozen Shirt',
    points: 93942,
    image: 'https://loremflickr.com/640/480/fashion',
    is_redemption: true,
    id: '88',
    query:
      'query query_allProducts_id377 {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}\n',
    variables: {},
    operationName: 'query_allProducts_id377',
  },
  {
    createdAt: '2023-03-11T12:38:14.137Z',
    product: 'Small Metal Keyboard',
    points: 88721,
    image: 'https://loremflickr.com/640/480/city',
    is_redemption: false,
    id: '89',
    query:
      'query a {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}\n',
    variables: {},
    operationName: 'a',
  },
  {
    createdAt: '2023-03-11T23:28:08.121Z',
    product: 'Generic Rubber Tuna',
    points: 71615,
    image: 'https://loremflickr.com/640/480/sports',
    is_redemption: false,
    id: '90',
    query:
      'query a {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}\n',
    variables: {},
    operationName: 'a',
  },
  {
    createdAt: '2023-03-11T13:20:22.106Z',
    product: 'Incredible Granite Mouse',
    points: 59153,
    image: 'https://loremflickr.com/640/480/business',
    is_redemption: true,
    id: '91',
    query:
      'query a {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}\n',
    variables: {},
    operationName: 'a',
  },
  {
    createdAt: '2023-03-11T10:40:51.661Z',
    product: 'Handmade Plastic Salad',
    points: 42873,
    image: 'https://loremflickr.com/640/480/fashion',
    is_redemption: true,
    id: '92',
    query:
      'query a {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}\n',
    variables: {},
    operationName: 'a',
  },
  {
    createdAt: '2023-03-11T10:54:22.757Z',
    product: 'Modern Plastic Pizza',
    points: 12583,
    image: 'https://loremflickr.com/640/480/nightlife',
    is_redemption: false,
    id: '93',
    query:
      'query a {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}\n',
    variables: {},
    operationName: 'a',
  },
  {
    createdAt: '2023-03-12T00:40:38.584Z',
    product: 'Handmade Granite Cheese',
    points: 44147,
    image: 'https://loremflickr.com/640/480/city',
    is_redemption: true,
    id: '94',
    query:
      'query a {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}\n',
    variables: {},
    operationName: 'a',
  },
  {
    createdAt: '2023-03-11T18:50:23.287Z',
    product: 'Incredible Cotton Table',
    points: 45611,
    image: 'https://loremflickr.com/640/480/technics',
    is_redemption: true,
    id: '95',
    query:
      'query a {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}\n',
    variables: {},
    operationName: 'a',
  },
  {
    createdAt: '2023-03-12T01:49:50.517Z',
    product: 'Incredible Fresh Chicken',
    points: 14608,
    image: 'https://loremflickr.com/640/480/nature',
    is_redemption: true,
    id: '96',
    query:
      'query a {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}\n',
    variables: {},
    operationName: 'a',
  },
  {
    createdAt: '2023-03-12T02:34:39.270Z',
    product: 'Refined Cotton Hat',
    points: 10059,
    image: 'https://loremflickr.com/640/480/animals',
    is_redemption: true,
    id: '97',
    query:
      'query a {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}\n',
    variables: {},
    operationName: 'a',
  },
  {
    createdAt: '2023-03-11T22:51:04.437Z',
    product: 'Refined Plastic Fish',
    points: 56025,
    image: 'https://loremflickr.com/640/480/nature',
    is_redemption: true,
    id: '98',
    query:
      'query a {\n  allProducts {\n    id\n    name\n    description\n    price\n    imageUrl\n  }\n}\n',
    variables: {},
    operationName: 'a',
  },
  {
    createdAt: '2023-03-11T11:40:56.512Z',
    product: 'Electronic Rubber Cheese',
    points: 52321,
    image: 'https://loremflickr.com/640/480/fashion',
    is_redemption: false,
    id: '99',
    query: '{\n  products\n}',
    variables: {},
    operationName: null,
  },
  {
    createdAt: '2023-03-11T16:17:33.482Z',
    product: 'Fantastic Plastic Hat',
    points: 76717,
    image: 'https://loremflickr.com/640/480/abstract',
    is_redemption: false,
    id: '100',
    query: '{\n  products\n}',
    variables: {},
    operationName: null,
  },
];
